### ISSUE TITLE
Dynamic loading truststore certificates

### ISSUE THREAD

**Issue by TMain-Tomi** [phax/phase4#129]
Dear @phax ,

I used phase4-spring-boot-demo to release AS4 server now. And it runs successful.
But I meet a problem when I want to dynamic loading truststore certificates.
I config the truststore like this:
>>org.apache.wss4j.crypto.merlin.truststore.type=JKS
org.apache.wss4j.crypto.merlin.truststore.file=test.jks
org.apache.wss4j.crypto.merlin.truststore.password=test

when I add/delete a cert from test.jks, will  run the following logic:
>>   **Path publicCertPath = new File("D:\\phase4-as4\\src\\main\\resources\\test.jks").toPath()
        String partnerPwd = 'test'**
         // Add all certificates to trust store
        **KeyStore trustKeyStore = AS4KeystoreUtils.load(publicCertPath, partnerPwd)
        KeyStore keyStore = AS4CryptoFactoryProperties.getDefaultInstance ().getKeyStore ()
        AS4XServletHandler handler = new AS4XServletHandler ();
        AS4CryptoFactoryInMemoryKeyStore cf = new AS4CryptoFactoryInMemoryKeyStore(keyStore, 'test','test', trustKeyStore);
        handler.setCryptoFactorySupplier(() -> cf);**

But when I add a new cert into test.jks, the server doesn't identify it, need to re-run the server.
May you give me some advices? thanks.

Best Regards,
Tomi Lin

_Originally posted by @TMain-Tomi in https://github.com/phax/phase4/discussions/95#discussioncomment-5974189_

**Comment by phax** [comment]
Well, I think the easiest way to do this, is to move all the loading part into the CryptoFactpry supplier, like this:

```java
handler.setCryptoFactorySupplier(() ->{
        Path publicCertPath = new File("D:\phase4-as4\src\main\resources\test.jks").toPath()
        String partnerPwd = 'test'
        // Add all certificates to trust store
        KeyStore trustKeyStore = AS4KeystoreUtils.load(publicCertPath, partnerPwd)
        KeyStore keyStore = AS4CryptoFactoryProperties.getDefaultInstance ().getKeyStore ()
        AS4XServletHandler handler = new AS4XServletHandler ();
        AS4CryptoFactoryInMemoryKeyStore cf = new AS4CryptoFactoryInMemoryKeyStore(keyStore, 'test','test', trustKeyStore);
         return cf;
});
```

**Comment by phax** [comment]
Was moved to discussions #130
