### ISSUE TITLE
AS4 message is not encrypted with the receiver's Cert?

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/phase4#13]
Seems the as4 messages sent are not encrypted with the receiver's cert, by looking in AS4ClientUserMessage.buildMessage . Am I right? If this is the case how may I get it encrypted with teh receiver's cert?

**Comment by phax** [comment]
unfortunately you are correct.
this is already fixed in the current HEAD revision (0.9.0-SNAPSHOT).
I will publish a new release as soon as I managed to pass the CEF conformance test....

**Comment by phax** [comment]
See `AS4CryptParams.setAlias` or `AS4CryptParams.setCertificate` in the 0.9.0 codebase
