### ISSUE TITLE
aSecurityProvider not customizable in SOAPHeaderElementProcessorRegistry

### ISSUE THREAD

**Issue by sopgreg** [phax/phase4#154]
This was added in commit 87d19b8470a4ec5869781c698de659535fb5dc66, but there is no way to set the provider. Is there something missing to this commit?

![grafik](https://github.com/phax/phase4/assets/33895520/84f5c1d6-d536-412b-8b23-f7d82f933d4d)

**Comment by phax** [comment]
I admit, that's a bit tricky to do.
You need to configure it into the `AS4XServletHandler` via an instance of `AS4IncomingSecurityConfiguration`. See belows pseudo code:
```java
   final Supplier <? extends IAS4CryptoFactory> aCryptoFactorySupplier = ...;
    // Customize WSSConfig and RequestData via this object:
    final IAS4DecryptParameterModifier aDecryptParameterModifier = new IAS4DecryptParameterModifier () { ... };
    final AS4XServletHandler aHandler = new AS4XServletHandler ()
        .setCryptoFactorySupplier (aCryptoFactorySupplier)
        .setPModeResolver (new MyPModeResolver ())
// Here the SecurityProvider geset set
        .setIncomingSecurityConfiguration (new AS4IncomingSecurityConfiguration ()
                                               .setSecurityProvider (PBCProvider.getProvider ())
                                               .setDecryptParameterModifier (aDecryptParameterModifier));
    handlerRegistry ().registerHandler (EHttpMethod.POST, aHandler);
```

**Comment by sopgreg** [comment]
That's what we are already doing. What is the point in `SOAPHeaderElementProcessorWSS4J` then? The `null` security provider is used here:

`aRequestData.setSignatureProvider (m_aSecurityProvider);`

**Comment by phax** [comment]
You are so right - thanks for pointing that out. Some unfinished code that was can never get useful. Now all the missing pieces are (hopefully) put together.
For the incoming configuration, stick to the above code.
For the outgoing configuration, the respective `AS4IncomingSecurityConfiguration` object is build automatically from the data available. That should solve the issue.

**Comment by sopgreg** [comment]
Great, thanks! Will check this later.

**Comment by sopgreg** [comment]
Works, thanks!

**Comment by phax** [comment]
Excellent thanks. So I would br building the 2.2.0 release then, or do you have some testing ahead?

**Comment by sopgreg** [comment]
Everything is looking good so far, go ahead :)
