### ISSUE TITLE
Dependency conflicts ph-oton-app and ph-web / NoSuchMethodError

### ISSUE THREAD

**Issue by sopgreg** [phax/phase4#156]
It seems the current SNAPSHOT has dependency conflicts which result in a `NoSuchMethodError` for incoming requests because of recent changes in the `ServletHelper` class in `ph-servlet` between 10.1.4 and 10.1.5.

I guess `ph-oton-app` needs to be updated to `9.1.4` to use `ph-servlet` 10.1.5.

![grafik](https://github.com/phax/phase4/assets/33895520/3bf47d60-54ac-460c-8fea-99ba58e65ee1)

```
Exception handling request to /: java.lang.NoSuchMethodError: 'java.lang.String com.helger.servlet.ServletHelper.getRequestMethod(jakarta.servlet.http.HttpServletRequest)'
	at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:474)
```

**Comment by phax** [comment]
Bloody Maven version resolution algorithm....

Thanks for pointing it out. I will create a ph-oton 9.1.4 to fix the issue.

**Comment by phax** [comment]
Okay, so the new dependency is in. May I ask @sopgreg  "how" you are including phase4 in your project?
For Maven it makes a difference, if you include the "BOM" in the `<dependencyManagement>` or whether you include it directly in the `<dependencies>` element. Additionally of course the order matters, and the dependencies with the least transitive dependencies should go first with the desired version.

hth

**Comment by sopgreg** [comment]
It is a bit of a mess right now to be honest. Some dependencies are defined directly with their version in the respective modules, some are defined in the `<dependencyManagement>` in the base POM. I cleaned this up so every dependency is defined with its version in `<dependencyManagement>` in the base POM and the respective modules only reference these.

**Comment by phax** [comment]
Okay, so does the update work for you? Can this ticket be closed?

**Comment by sopgreg** [comment]
Yes it does work, thank you!
