### ISSUE TITLE
Add custom keystore type problem

### ISSUE THREAD

**Issue by Stefan4112** [phax/phase4#157]
For the HSM product we must use a custom keystore type.
In the class **AS4CryptoProperties** the following methods should use the interface IKeyStoreType instead of EKeyStoreType:

public final AS4CryptoProperties setKeyStoreType (@Nullable final EKeyStoreType eType)
public final AS4CryptoProperties setTrustStoreType (@Nullable final EKeyStoreType eType)

**Comment by phax** [comment]
Okay, and using `EKeyStore.PKCS11 is not sufficient? What additional information do you need there?

**Comment by Stefan4112** [comment]
We use the vendor specific type "CryptoServer" - not PKCS11.

It was one of our first changes, but after all changes with the new BDEW profile I do not know if this value is used somewhere, is it?

**Comment by phax** [comment]
Okay thanks - I will make the necessary changes. As this is a breaking API change, it will lead to version 2.3.x

**Comment by phax** [comment]
@Stefan4112 Well no - after careful consideration it does not make sense ;-)

The class `AS4CryptoProperties` delivers the necessary elements for the crypto factory from properties. In textual proprties, the generic `IKeyStoreType` cannot be represented safely, so we're stuck with `EKeyStoreType` here.

Instead I suggest you switch to `AS4CryptoFactoryInMemoryKeyStore` as the implementation of `IAS4CryptoFactory` and place the previously read key store and trust store inside this object. Please let me know if that makes sense to you

**Comment by Stefan4112** [comment]
Good idea. It will do it.
Using our own implementation, that could also be a nice place to add some special logic we need in our project (non BDEW specific stuff).
