### ISSUE TITLE
Content-Disposition not appearing in final output

### ISSUE THREAD

**Issue by evilanf** [phax/phase4#16]
The AddAttachments routine is calling _addOutgoingHeaders and it all appears to be setting the Content-Disposition but the final output is not showing the Content-Disposition file.

**Comment by phax** [comment]
Peppol has a specific statement on this in chapter 4.10 of https://docs.peppol.eu/edelivery/as4/specification/ 
> The "Content-Disposition" MIME header as described in section 5.1.9 of [AS4-Profile] SHALL NOT be used to exchange the filename of an attached payload. AS4 implementations not supporting removal of the MIME header MUST use payload.xml as filename.
I therefore created an overload of `WSS4JAttachment.createOutgoingFileAttachment` that can take an explicit filename.

Additionally all custom headers are now added to the MIME part. Please confirm with the latest 0.9.3 SNAPSHOT
