### ISSUE TITLE
SKI_KEY_IDENTIFIER should be used in BDEW profile in crypto params

### ISSUE THREAD

**Issue by problemzebra2** [phax/phase4#167]
`cryptParams ().setKeyIdentifierType (DEFAULT_KEY_IDENTIFIER_TYPE);` seems to be wrong. According to the BDEW profile SKI_KEY_IDENTIFIER should be used:

![grafik](https://github.com/phax/phase4/assets/46046993/dc43f3a7-612f-4b9e-88a1-4fe635f37b75)

**Comment by phax** [comment]
Ah yes, I see.
For signing, it is BST, for crypting it is SKI

**Comment by phax** [comment]
Thanks. Will be part of the upcoming 2.3.0 release
