### ISSUE TITLE
phase4-servlet receipt references non-existent attachment in ds:SignedInfo

### ISSUE THREAD

**Issue by thelateperseus** [phax/phase4#17]
I'm testing my own eInvoicing code by sending an AS4 message to phase4-servlet and I noticed that the receipt generated by phase4-servlet doesn't seem to be valid. The receipt message has no attachments, but includes a reference to the original `<eb:UserMessage>` attachment in `wsse:Security/ds:Signature/ds:SignedInfo`.

```
<ds:Reference URI="cid:partaba1efd30000016e149a6ed400000004_1">
  <ds:Transforms>
    <ds:Transform Algorithm="http://docs.oasis-open.org/wss/oasis-wss-SwAProfile-1.1#Attachment-Content-Signature-Transform"/>
  </ds:Transforms>
  <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
  <ds:DigestValue>v5F7qa6envmNTvKbnUaPJ5+6pHZHWQvQJbmhfr4hU+s=</ds:DigestValue>
</ds:Reference>
```

My signature verification code fails because there is no attachment on the receipt. If I understand correctly, this response is invalid under AS4 because this `<ds:Reference>` shouldn't be present. However, let me know if I've missed something and this response is valid somehow.

Removing [line 662 from AS4RequestHandler](https://github.com/phax/phase4/blob/master/phase4-servlet/src/main/java/com/helger/phase4/servlet/AS4RequestHandler.java#L662) fixes the problem, and the remaining `<ds:Reference>` elements (referring to the `<eb:Messaging>` header and the SOAP Body) which can be correctly verified.

See attached for the bad and corrected responses.
* [badResponse.txt](https://github.com/phax/phase4/files/3781007/badResponse.txt)
* [correctedResponse.txt](https://github.com/phax/phase4/files/3781008/correctedResponse.txt)

Thanks for building phase4 - it's been very handy for my testing!

**Comment by phax** [comment]
@thelateperseus I get the bug, but I don't understand how it happens.
Inside the phase4-lib code, it is an empty list... I will need to dig deeper on that one

**Comment by phax** [comment]
The problem was, that the `ExampleReceiveMessageProcessorSPI` passes the "incoming attachments" as "response attachments" which is considered wrong. This was only needed for testing, but should not happen in production. That should resolve your issue.

**Comment by thelateperseus** [comment]
Can confirm that it's fixed now. Thanks!
