### ISSUE TITLE
Receiving a Test service (ping) message should invoke SPIs

### ISSUE THREAD

**Issue by problemzebra2** [phax/phase4#175]
When receiving a Test service (ping) message the SPIs are not invoked:

![grafik](https://github.com/phax/phase4/assets/46046993/b123f5ac-ac12-4985-9db1-8d4e72e8452e)

For the BDEW profile it is necessary to invoke the SPIs because the Test service is usually called with a payload and the message is used to check if signing an encryption is actually working.

Is it possible to remove this check at all or are there any requirements for this in other AS4 profiles?

Another possible solution would be to make this configurable. Where would one implement this?

**Comment by phax** [comment]
Sorry, this one does not make it into 2.5.0 - I need to investigate further

**Comment by phax** [comment]
This is now configured into `boolean IAS4Profile.isInvokeSPIForPingMessage()` and enabled for BDEW by default. Part of release 2.5.3
