### ISSUE TITLE
IAS4SignalMessageConsumer: Add possibility to validate the signal (Signature)

### ISSUE THREAD

**Issue by phax** [phax/phase4#177]
### Discussed in https://github.com/phax/phase4/discussions/176

<div type='discussions-op-text'>

<sup>Originally posted by **sopgreg** October 10, 2023</sup>
Similiar to https://github.com/phax/phase4/issues/162, it would be helpful to have a possibility to validate the Signal/Receipt received on the outgoing side, e.g. through the `SignalMessageConsumer`

Right now, the signature of `IAS4SignalMessageConsumer#handleSignalMessage` looks like this:

`void handleSignalMessage (@Nonnull Ebms3SignalMessage aSignalMsg) throws Phase4Exception;`

If the signature looked like this, it would be possible to check the message state for `isSoapSignatureChecked`/`isSoapDecrypted`:

`void handleSignalMessage (@Nonnull Ebms3SignalMessage aSignalMsg, @Nonnull IAS4MessageState state) throws Phase4Exception;`

Technically, this should be possible quite easily by changing the result of `com.helger.phase4.servlet.AS4IncomingHandler#parseSignalMessage` to return both the `Ebms3SignalMessage` and the `IAS4MessageState` and return this to the `SignalMessageConsumer`.

Looking forward to reading your opinion in this requirement.</div>

**Comment by phax** [comment]
Part of the 2.5.0 release

**Comment by sopgreg** [comment]
Thanks. I looked into the commit - you included the `IAS4IncomingMessageMetadata ` into the interface method. But the `IAS4MessageState` is not included there.

Is this an oversight or did I miss something?

**Comment by phax** [comment]
My mistake - I mixed up the interfaces ;-) I add that one as well.

**Comment by phax** [comment]
@sopgreg  hope that suits you now :)

**Comment by sopgreg** [comment]
Seems fine, we will have a look at it. Thanks! :)
