### ISSUE TITLE
Not possible to send BDEW path switch messages because a payload is always required

### ISSUE THREAD

**Issue by problemzebra2** [phax/phase4#180]
Currently it is not possible to send a path switch message withoud payload.

![grafik](https://github.com/phax/phase4/assets/46046993/34de472f-aa38-4ead-8399-62309f085b03)

![grafik](https://github.com/phax/phase4/assets/46046993/07f10598-8608-4619-99e8-2474404c53f8)

According to the BDEW AS4 profile a payload is not allowed. The german "MÜSSEN keine..." is a very bad wording by the BDEW...
![grafik](https://github.com/phax/phase4/assets/46046993/5b755f8d-50d7-410e-a051-8d7dfb89f668)
-> https://www.edi-energy.de/index.php?id=38&tx_bdew_bdew%5Buid%5D=2091&tx_bdew_bdew%5Baction%5D=download&tx_bdew_bdew%5Bcontroller%5D=Dokument&cHash=c3338aa8cb55e5946a1b0d1dbfdc2e0a ( -> 2.3.7)

**Comment by problemzebra2** [comment]
would #181 be enough as a fix for this (not tested)?

**Comment by phax** [comment]
Yes, #181 basically fixes the issue - thanks.
Question: is there a BDEW parameter, when the payload is mandatory? If so, that could be checked in https://github.com/phax/phase4/blob/master/phase4-bdew-client/src/main/java/com/helger/phase4/bdew/Phase4BDEWSender.java#L200

**Comment by problemzebra2** [comment]
I think that the payload is mandatory for all services except the patch switch services (both request and confirmation).

**Comment by phax** [comment]
Now the check is done and complete
