### ISSUE TITLE
SOAP with attachments messages without payload for BDEW patch switches

### ISSUE THREAD

**Issue by problemzebra2** [phax/phase4#186]
According to the BDEW AS4 profile (https://www.edi-energy.de/index.php?id=38&tx_bdew_bdew%5Buid%5D=2091&tx_bdew_bdew%5Baction%5D=download&tx_bdew_bdew%5Bcontroller%5D=Dokument&cHash=c3338aa8cb55e5946a1b0d1dbfdc2e0a) all messages must be of type "SOAP with attachments" even if there is no payload (path swich messages):

![grafik](https://github.com/phax/phase4/assets/46046993/078920f5-7632-41e8-8c97-567d1cf573b8)

Most market participants reject messages with  non emtpy SOAP bodies or simple/plain SOAP messages

**Comment by phax** [comment]
Honestly, I think this is a non-compliance on their side, as the requirement to use MIME (SOAP with Attachments) doesn't seem to be formalized anywhere, but let me see what I can do to enforce this for BDEW

**Comment by phax** [comment]
This is a first shot, without any tests yet - please crosscheck if it suits your needs.

**Comment by phax** [comment]
Together with the additional commit, this looks good and will be part of the upcoming 2.5.1 release
