### ISSUE TITLE
Adding support for Spring profiles in Spring Phase4

### ISSUE THREAD

**Issue by tonytram** [phax/phase4#191]
Dear Philip,

First of all I would like to say thank you for your amazing effort on Phase4. Currently, our company is using Phase4 as our Peppol solution. I'm the man who is in charge of the implementing of the integration. I would like to use Spring profiles for our environments when deploying to production or other systems for testing. I do see that in the core of Phase4 you are using, all configured values are getting through **AS4Configuration.getConfig().getConfiguredValue("$name")**, and this will return a value of the property whose name matches in the application.properties file. My question is that is there anyway to combine getting values from AS4Configuration and Spring profiles (through @Value($name))

Thank you so much for your help.

**Comment by phax** [comment]
@tonytram Thanks for your feedback.
phase4 is designed to be independent of specific frameworks like SpringBoot or any other framework. That guarantees its usability in different environments like AWS Lambda etc. That also means, that phase4 does not use the SpringBoot configuration property management.

What you are trying to achieve can also be achieved with "phase4 native" :) phase4 configuration is based on https://github.com/phax/ph-commons/wiki/ph-config and so provides you with different ways to provide your configuration items. You can provide them via Java System Properties, Environment Variables or via properties in a file (see https://github.com/phax/phase4/wiki/Configuration for how ph-config is used in phase4).

So you may want use the configuration property `config.file` to define a different file containing the phase4 specific properties.

**Comment by tonytram** [comment]
Thank you for your reply. Actually I have read the Wiki and the source code, but I don't have any ideas to implement it (I totally newbie in Java :) ). So example code how can archive it will be great help. Thank you so much

**Comment by tonytram** [comment]
Dear @phax ,
I also want to change the certificate information according to environments as well. Might I consult you in which place that is safe to override the certification information?

**Comment by phax** [comment]
If you are using phase4 with SpringBoot I suugest you separate all the phase4 specific properties into a separate file called `phase4.properties` and leave the SpringBoot properties in `application.properties` - both in the same folder.
For development you create a file `phase4.dev.properties` and set the environment variable `CONFIG_FILE` in your IDE (refer to the respecitve manual of the IDE how to) to the value `phase4.dev.properties` (you may also use absolute paths there)

And yes, by having separate configuration files, you can also refer to different key stores and trust stores

**Comment by tonytram** [comment]
Thank you so much @phax. To set the configuration file using CONFIG_FILE is working for me. Might there be a better way which sticks to Spring profiles rather than this approach?

**Comment by tonytram** [comment]
The example is really helpful for me to start with my wrapper. Thank you so much and really appreciated your help @phax
