### ISSUE TITLE
aAPCertificate parameter in IPhase4PeppolCertificateCheckResultHandler is Nullable

### ISSUE THREAD

**Issue by Florianisme** [phax/phase4#206]
Hi Philip,

I have encountered a NPE while sending an outbound Peppol message because I relied on the `@Nonnull` annotation in `IPhase4PeppolCertificateCheckResultHandler` for the `@Nonnull X509Certificate aAPCertificate` parameter.

```java
java.lang.NullPointerException: Cannot invoke "java.security.cert.X509Certificate.getSubjectX500Principal()" because "certificate" is null at 
de.i.p.o.OutboundMessageProcessor.lambda$buildCertificateConsumer$3(OutboundMessageProcessor.java:160) at 
com.helger.phase4.peppol.Phase4PeppolSender$AbstractPeppolUserMessageBuilder.finishFields(Phase4PeppolSender.java:801) at 
com.helger.phase4.peppol.Phase4PeppolSender$Builder.finishFields(Phase4PeppolSender.java:1344) at 
com.helger.phase4.sender.AbstractAS4MessageBuilder.sendMessage(AbstractAS4MessageBuilder.java:831) at 
com.helger.phase4.sender.AbstractAS4UserMessageBuilder.sendMessageAndCheckForReceipt(AbstractAS4UserMessageBuilder.java:798) 
```

Going through the code I can see where this is coming from:

`Phase4PeppolSender.java` `(m_bCheckReceiverAPCertificate` is false)
![image](https://github.com/phax/phase4/assets/7106869/d3ce09cf-126e-4936-bc5f-f56998c5d35e)

From this point onwards the certificate is declared as Nullable:
`AS4EndpointDetailProviderPeppol.java`
![image](https://github.com/phax/phase4/assets/7106869/064cd0c0-1da1-491c-9c5a-4961e99d67c2)

**Comment by phax** [comment]
Thanks, fixed in the upcoming 2.7.0 release.
All other parameters are indeed non-null.
