### ISSUE TITLE
Receiving WildCard Error

### ISSUE THREAD

**Issue by sakasaka19** [phax/phase4#209]
Phase4 is checking the ReceiverEndpoint when receiving a wildcard DocumentType,
However, since the pattern matching method is not used at that time, it results in an error.

Please apply the fixes that were previously made for sending to the receiving process.

phase4-peppol-servlet\src\main\java\com\helger\phase4\peppolServlet\Phase4PeppolServletMessageProcessorSPI.java - AS4 MessageProcessorResult
　The aReceiverEndpoint obtained by _getReceiverEndpoint on line 792 is null.

peppol-commons
　peppol-smp-client\src\main\java\com\helger\smpclient\peppol\ISMPServiceMetadataProvider.java
　　I guess it's like calling getWildcardServiceMetadataOrNull instead of getServiceMetadataOrNull used in line 180?

**Comment by phax** [comment]
Thanks @sakasaka19 for pointing that out - you are of course totally right

**Comment by sakasaka19** [comment]
Hi Philip

Thanks for always upgrading Phase4.
When do you plan to release the new Phase4 with this Issue supported?

I'm also trying to work out a schedule for offering AccessPoint with the new Phase 4 built in,
I would like to know if you have a rough schedule in mind.

**Comment by phax** [comment]
@sakasaka19 the respective update v2.7.3 will be released this week. I am just collecting different issues :)

**Comment by sakasaka19** [comment]
Thank you Philip

I'm looking forword new Phase4 .

**Comment by phax** [comment]
Will be part of the 2.7.3 release. Please use `Phase4PeppolServletConfiguration.setWildcardSelectionMode` to configure the respective wildcard selection mode.
