### ISSUE TITLE
Add the possibility to send an outside SBDH

### ISSUE THREAD

**Issue by phax** [phax/phase4#22]
In a comparable way as https://github.com/phax/as2-peppol-client/issues/5

**Comment by phax** [comment]
Part of the 0.9.6 release

**Comment by kukel** [comment]
Does this still mean I need to manually parse the SBD(H) and retrieve the sender, recipient documenttypeid etc? Just that the SBDH is not created? I thought with your AS2 solution this was not needed or am I wrong?

**Comment by phax** [comment]
If you want phase4 to build your SBDH, you use `Phase4PeppolSender.builder ()` whereas if you already have an SBDH, you use `Phase4PeppolSender.sbdhBuilder()` to set the necessary settings. The difference is in validation etc.
The setup here is not comparable to the AS2 solution and was rebuild from scratch (hopefully simpler).

**Comment by phax** [comment]
@kukel Would something like this suffice:
````java
  @Nonnull
    public SBDHBuilder payloadAndMetadata (@Nonnull final PeppolSBDHDocument aSBDH)
    {
      ValueEnforcer.notNull (aSBDH, "SBDH");
      return senderParticipantID (aSBDH.getSenderAsIdentifier ()).receiverParticipantID (aSBDH.getReceiverAsIdentifier ())
                                                                 .documentTypeID (aSBDH.getDocumentTypeAsIdentifier ())
                                                                 .processID (aSBDH.getProcessAsIdentifier ())
                                                                 .payload (new SBDMarshaller ().getAsBytes (new PeppolSBDHDocumentWriter ().createStandardBusinessDocument (aSBDH)));
    }
```

or what is your input format`of the SBDH?

**Comment by phax** [comment]
Part of 0.10.2 release
