### ISSUE TITLE
Validating NRRs against sent or received messages

### ISSUE THREAD

**Issue by beth-soptim** [phax/phase4#220]
It would be very useful if Phase4 would offer a functionality to validate an NRR against the sent message (full SOAP header, SOAP body, Payload).

**Comment by phax** [comment]
That sounds like a good plan. This check should contain
* Verification of `MessageId` and `RefToMessageId`
* Check that the SignalMessage is a Receipt with NRR
* Check if the signature `Reference` elements from the source message are present in the NRR information of the receipt

**Comment by phax** [comment]
@problemzebra2 better late than never, but it will be integrated in the next version of the 3.0.0 branch. Additional to the main checking logic, I added a `IValidatingAS4SignalMsgConsumerResultHandler` interface with which you can customize the activities needed on failure.

What is missing is passing the validation result handler through to all APIs - afterwards I will close this ticket.

**Comment by phax** [comment]
Shit - I missed that one for the 3.0.0 release - everything was nicely prepared, except for the setters in the builder :(
Btw. the final name is now `IAS4SignalMessageValidationResultHandler` for the respective interface.

**Comment by phax** [comment]
Will be part of the upcoming 3.0.1 release.

Just add e.g. ` .signalMsgValidationResultHdl (new LoggingAS4SignalMsgValidationResultHandler ())` in your UserMessage or PullRequest builder
