### ISSUE TITLE
Sending Einvoice to SG ABN resulting in Invalid Certificate Error

### ISSUE THREAD

**Issue by duke-nuke** [phax/phase4#221]
Hi 

I am trying to send an einvoice to Singapore ABN , but getting below Error 
<eb:Error category="Unpackaging" errorCode="EBMS:0009" origin="ebms" refToMessageInError="637b8d31-8115-4895-8398-e5cffa473d31@phase4" severity="error" shortDescription="InvalidHeader"><eb:ErrorDetail>Error during certificate path validation: No trusted certs found
cause: Error during certificate path validation: No trusted certs found</eb:ErrorDetail></eb:Error>

I am able to send einvoice to australia and nz ABNs 
i have contacted vendor they are saying i am not using SG Peppol BIS 3.0
any help would be appreciated 

regards
Khurram

**Comment by phax** [comment]
Hi, this message usually has nothing to do with the SG Peppol BIS 3.0 content.
The error message `Error during certificate path validation: No trusted certs found` indicates, that something is wrong with the certificates used. Either you are signing with the wrong certificate, or you are encrypting with the wrong certificate.

Can you please post the the following here and I will check some setup details:
* Participant ID of the receiver 
* whether it is test or production Peppol Network

**Comment by duke-nuke** [comment]
0195:SGTSTIMDADEMO02

**Comment by phax** [comment]
Okay, so they are running Oxalis 5.5 in the production Network only.
* Are you also using the production certificate in your code?
* Do you always do an SMP lookup before sending?

**Comment by duke-nuke** [comment]
Are you also using the production certificate in your code?
Yes Production AP Certificate ( i tried sending another Participant ID and it was success SGTSTIMDADEMO08


Do you always do an SMP lookup before sending?

Yes the logs suggest that lookup is always performed .

**Comment by phax** [comment]
Hmm, then I am out of ideas, if other transmissions work.
When you try sending a correct Peppol SG document, does the error message change?

**Comment by duke-nuke** [comment]
thanks issue is resolved 
i was signing the message with test certificate on Production

**Comment by phax** [comment]
Ah okay - that makes sense and good that it causes an error.
However, this should have lead to issues for the other receivers as well, you mentioned earlier.... MAybe you can ping them and let them know, that they have an issue.

Closing this issue now
