### ISSUE TITLE
Better AS4 error message when duplicate MessageId has been detected

### ISSUE THREAD

**Issue by problemzebra2** [phax/phase4#223]
Currently phase4 sends an error message with a very generic error message:

![grafik](https://github.com/phax/phase4/assets/46046993/989b96a6-2eb4-485c-914e-840e570ed416)

It would be nicer if the ErrorDetail would contain a text like "Duplicate MessageId detected".

**Comment by phax** [comment]
The error message, also for duplicate messages was improved via #198 and implemented on 7.12.2023 and this was part of the 2.6.0 release (see https://github.com/phax/phase4/releases/tag/phase4-parent-pom-2.6.0 )
Are you sure, it is a duplicate message ID?

See https://github.com/phax/phase4/blob/master/phase4-lib/src/main/java/com/helger/phase4/servlet/AS4RequestHandler.java#L1429 for the current code...

**Comment by phax** [comment]
Okay, so the issues was resolved, as it was a customization on side of @problemzebra2
