### ISSUE TITLE
Dynamically set responder address for incoming messages

### ISSUE THREAD

**Issue by koes-soptim** [phax/phase4#233]
In our software, we use `IPmodeResolver.getPModeOfID` to construct the PMode for any incoming AS4 message.
Anyway, the parameter `sAddress`, which represents our "own" AS4 endpoint address(es) is always _null_. 
I found out that the address can only be configured globally ("_phase4.endpoint.address_") and is queried in `SOAPHeaderElementProcessorExtractEbms3Messaging`.

There is one issue: For the BDEW profile, the software manufacturers have to use dynamic 
addresses (like https://1111111111111.company.cloud, https://2222222222222.company.cloud) with SNI, so the AS4 endpoint can change with any incoming message.

Could you provide any way (e.g. a callback?) to handle this dynamically?

Kind regards,
Robin

**Comment by phax** [comment]
Thanks, I will integrate this in v3

**Comment by phax** [comment]
Will be part of the first 3.0.0 release
