### ISSUE TITLE
How can I retrieve the sent response in servlet?

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/phase4#24]
I would like to capture the reply message upon an incoming one in the webapp. How would I go about doing that?

**Comment by phax** [comment]
Hi,
you are using `phase4-server-webapp` atm - right?
In general you can use the dumper, to debug the byte streams:
```
AS4DumpManager.setIncomingDumper (new AS4IncomingDumperFileBased ());
AS4DumpManager.setOutgoingDumper (new AS4OutgoingDumperFileBased ());
```
or at what stage do you need it?
Thanks and BR,
  Philip

**Comment by phax** [comment]
Hi Alexandru,
did that answer your question? The next verison (0.9.6) will come with the possibility to specify an outgoing dumper "per message" and not necessarily globally.
// Philip
