### ISSUE TITLE
Any way to get the response MDN when running the client?

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/phase4#25]
I tried intercepting the response MDN when I send a document through with the client but I only get the raw response with the encrypted/signed envelope. I don't see a way to extract the actual reply sent. Am I missing something?

**Comment by phax** [comment]
As you've identified in #26 there is a way using `IPhase4PeppolResponseConsumer` (as of 0.9.6) to get the `byte[]` with the response payload.

Additionally the callback `IPhase4PeppolSignalMessageConsumer` is available to get the parsed callback (which still has issues when a MIME message is sent back).

So I guess, this one can be closed - right?
