### ISSUE TITLE
Separate builder in new DBNAlliance client to support creating XHE envelope externally and feed it to phase4

### ISSUE THREAD

**Issue by PriyanjaleeSilva** [phax/phase4#255]
We are currently trying to integrate phase4-dbnalliance-client 2.8.0. In our flow we are creating the XHE/SBDH envelope externally and feed it into phase4. In Peppol profile we use `sbdhBuilder` in `Phase4PeppolSender`. But in new DBNA client, we are not able to find a similar way to feed the XHE envelope. 
Could you please provide a separate builder or a method in `Phase4DBNAllianceSender` for this?

Kind Regards,
Manusha.

**Comment by phax** [comment]
This is absolutely a good suggestion. Will do it in one of the next versions

**Comment by phax** [comment]
`Phase4DBNAllianceSender.xheBuilder ().payloadAndMetadata (DBNAllianceXHEData)` will (hopefully) do the trick.
This is part of the v3.0.0 release.
