### ISSUE TITLE
bcmail artifact seems to be unused (and in wrong non Jakarta version)

### ISSUE THREAD

**Issue by problemzebra2** [phax/phase4#271]
Hi,

the `bcmail` artifact seems to be unused. Also `bcmail` uses javax namespace, `bcjmail` uses the jakarta namespace (and if required should be used instead).

I guess that this dependency can be removed.

**Comment by phax** [comment]
Will be fixed in version 2.8.4.
Really wondering why that didn't pop up earlier...
Thanks for bringing that to my attention
