### ISSUE TITLE
versioning issues

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/phase4#29]
Hi Phil,
Happy New year!
I see an issue with versions of dependencies. I loaded teh entire project ad imported it into intellij and I see in the libraries section multiple versions of a dependency:
com.google.guava:guava:19.0
com.google.guava:guava:20.0
com.helger:pepol-smp-client:7.0.4
com.helger:pepol-smp-client:7.0.6

and the list can go on. 

I think one of the parent poms referenced may be the culprits.

**Comment by phax** [comment]
Well that should be resved automatically by Maven... I will check it anyway

**Comment by phax** [comment]
Hi Alex,
sorry that one slipped through :(
I cross checked and I don't see any guava on my side.
What project are you exactly referring to?

Thanks, Philip

**Comment by phax** [comment]
Hi Alex,
closing this one due to inactivity.
If this is still an issue, feel free to re-open it.
BR, Philip
