### ISSUE TITLE
How to receive message level response (MLR) in phase4-peppol-client?

### ISSUE THREAD

**Issue by jamalsa** [phax/phase4#31]
I'm using phase4-peppol-client to send invoice to an access point. The invoice is sent successfully and I got a receipt. But the receiver's contact person said that the invoice has an incorrect parameter and I can automatically get the error message if I enable receiving MLR. I try using methods setResponseConsumer and setSignalMsgConsumer from Phase4PeppolSender.Builder but cannot get the MLR. 

My question is how to receive MLR in phase4-peppol-client?

**Comment by phax** [comment]
Hi @jamalsa, there is a certain confusion in terms here :)

When you send an AS4 message out, it is a so called AS4 "UserMessage" and what you get back is an "AS4 Receipt" (in case of success) or an "AS4 Error" (in case of an error).

The "MLR" (short for "Message Level Response") you are searching is a separate Peppol BIS: https://docs.peppol.eu/poacc/upgrade-3/profiles/36-mlr/ - you need to register it at your SMP for receival (with your participant ID etc.). That also means that you need to have an AS4 server for receiving incoming messages.

hth, Philip

**Comment by jamalsa** [comment]
Hi @phax thank you for your response. I am new to AS4 and Peppol so still have a lot to learn. I will prepare an AS4 server and ask our SMP for registration. Thank you.

**Comment by phax** [comment]
@jamalsa You are welcome. Peppol is not too easy, but I hope it's all logical :) 
May I ask what company you are working for, so that I can list you at https://github.com/phax/phase4#known-users ?

**Comment by jamalsa** [comment]
We still at the testing stage so cannot disclose the name yet. After the application goes live I will ask my employer permission to list my company :)
