### ISSUE TITLE
Remove originalSender + finalRecipient from AS4IncomingHandler

### ISSUE THREAD

**Issue by pavelrotek** [phax/phase4#33]
Hi Philip, originalSender + finalRecipient is not mandatory for non CEF/PEPPOL profiles like ENTSOG.
Is it possible to move the mandatory check outside to CEF/PEPPOL validator?

Thank you,

Pavel

**Comment by phax** [comment]
Yes of course :) I already added myself a TODO in the code...

**Comment by phax** [comment]
Part of 0.9.13 release.

@pavelrotek can you eventually provide a profile library for ENTSOG?

**Comment by pavelrotek** [comment]
Great! Yes, i would like to contribute with ENTSOG profile (validator and client. should be enough in case of ENTSOG).  There are other things that could be done in the library, i'll contact you via mail direcly.
