### ISSUE TITLE
Add callback method to retrieve the generated raw SBD

### ISSUE THREAD

**Issue by RovoMe** [phax/phase4#34]
On using the `Phase4PeppolSender.Builder` and passing the bytes of the UBL via the builder's `setPayload(byte[])` method, there is currently no way to obtain the generated SBD. While technically the SBD could be obtained via the output stream that is fed into our customized `IAS4OutgoingDumper` implementation, further filtering and decryption are necessary. Especially the decryption part is probably the blocking part though as we do not have access to the targets private key unfortunately.

A callback method that is [invoked right after the SBD was generated](https://github.com/phax/phase4/blob/master/phase4-peppol-client/src/main/java/com/helger/phase4/peppol/Phase4PeppolSender.java#L1353) would therefore be highly appreciated. The callback should probably support deep copying of the SBD in order to prevent posterior changes done to the original SBD while handling the callback.

**Comment by phax** [comment]
Part of 0.9.13 release
