### ISSUE TITLE
Create a camel enpoint (sending and receiving)

### ISSUE THREAD

**Issue by kukel** [phax/phase4#37]
I've been trying to do this for Oxalis, but on the major issues (e.g. too much code and functionslity in one method) and no response to my issues etc...  I'm sort of fed up with them. Yes, it might be the most used in the world and they have coding wise some nice things but it is alsmost completely 'you need to do it our way' with some plugablility but not good integration in others systems. 

So I'd like to volunteer to make a peppol endpoint for usage in camel. Sending and receiving... So you can use all other features of camel as wel (including storate, routing etc...)... Interested?

**Comment by phax** [comment]
Totally :) That would be great 😄 
You want to do it specially for Peppol or as a very general solution?

**Comment by kukel** [comment]
Initially a peppol (indirect personal interest) but after that also an generic AS4 one.

**Comment by phax** [comment]
Okay cool. How do you want to progress?
Do you want to create your own repo, or do you want to work on a fork, or you want to have a feature branch here?
Find my email address in the pom.xml if you have questions....

**Comment by kukel** [comment]
Let me first do some local development. And no no need for my own repo. Better to have it with phase4.

**Comment by kukel** [comment]
This is why I dislike them... No reaction https://github.com/difi/oxalis/issues/444, https://github.com/difi/oxalis/issues/447  https://github.com/difi/oxalis/issues/446 (yes open-gdsn is #metoo ;-))

**Comment by phax** [comment]
@kukel do you have any update on this one or something that could be discussed?

**Comment by phax** [comment]
Closing this issue for now. @kukel  please re-open if you have some news for me.
