### ISSUE TITLE
Peppol-Client: Add posibility to add custom VES_REGISTRY for validation

### ISSUE THREAD

**Issue by traker9999** [phax/phase4#38]
It would be wonderfull if a custom VES_REGISTRY (e.g. Kosit XRechnung VESID) could be used for the peppol-client validation of payload (Phase4PeppolSender builder) . Currently its only possible to use PeppolValidation VESID.

**Comment by phax** [comment]
Lucky you, that was already implemented in the "0.10.1" release, that was published lately.
The "Builder" class of the phase4-peppol-client received a new method `validationRegistry(IValidationExecutorSetRegistry)` to do exactly that.

**Comment by traker9999** [comment]
perfect, thanks alot
