### ISSUE TITLE
[Question - Validation Configuration on phase4 receiver servlet]

### ISSUE THREAD

**Issue by jmrleal** [phax/phase4#51]
Hello Philip, I was wondering if there is an easy way to register a validation configuration on the receiver side?

**Comment by phax** [comment]
Well, on the receiver side, you basically have an SPI that you need to implement (`IAS4ServletMessageProcessorSPI`) - inside that SPI you can validate whatever you like.
Or what kind of validation did you have in mind?

**Comment by jmrleal** [comment]
I would like to validate the Business Message (Invoice) and only proceed if there were no errors. Else I would like to notify the sender. I saw that on the phase4 client we can register a validation configuration based on the phive engine that allows the client to verify if the invoice is well formed and complies with the peppol rules. I would like to do the same in the receiver and report back to the sender if there are errors.

**Comment by phax** [comment]
Okay, in that case you perform the validation in your SPI implementation of `IPhase4PeppolIncomingSBDHandlerSPI` (assuming you use this).
If the validation fails, you just throw an exception with the respective error message details.
Additionally you need to make sure, that the your SPI implementation overrides `boolean exceptionTranslatesToAS4Error ()` and returns `true`.
Does that help you?

**Comment by jmrleal** [comment]
I think that does help me indeed. So all I need to to is validate the document in my SPI and generate an exception to report the validation errors.

Thank you very much for your help, responsiveness and clear-cut answers!
