### ISSUE TITLE
For an inbound message, replace internal server error stack trace with an EBMS error message

### ISSUE THREAD

**Issue by amishregmi** [phax/phase4#52]
Currently, if we have some internal server failures, the stack trace is returned as the response. This might expose sensitive information and does not look like a standard message. Would be great if internal server errors are converted to an EBMS error message response, or if the responses can be intercepted and customized.

**Comment by phax** [comment]
Hi @amishregmi  do you eventually have an example response that you can share with me? Either here or by email?
Thx

**Comment by phax** [comment]
This would be part of the 1.3.2 release - feel free to test the latest SNAPSHOT, if it suits your needs now.
Basically I am catching exceptions closer to the source, and converting to an Error.
