### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by michielbdejong** [phax/phase4#54]
I'm creating a Docker image for this repo, starting from https://github.com/phax/phase4#building-from-source.

**Comment by michielbdejong** [comment]
Hm, actually since this is a library of components, it's not obvious what the Docker image should execute when you run it. For now, I'll try to make it run https://github.com/phax/phase4/blob/master/README.md#subproject-phase4-peppol-server-webapp with tomcat. Working on this in https://github.com/michielbdejong/phase4/commits/docker

**Comment by phax** [comment]
Exactly that is the point - because the "how to retrieve the document to send" and "what to do with the incoming message" is so implementation dependent, that a predefined Docker image would not help too much....

**Comment by michielbdejong** [comment]
I agree it will probably not have much use outside my peppol-testsuite project, but you never know. Maybe one day it helps someone. It's a piece of code that's specific to your project and not to my project, that's why I would like to upstream it to you, but it's up to you what you prefer.

Basically there are two options:
* include the Dockerfile somewhere in your repository (I would send you a PR for this)
* I create a separate phase4-docker repository which I maintain, you don't need to  review it, and people who search for "phase4 docker" would probably still easily find it (either from your docs or from Docker hub or from a web search)

Both options are fine with me! If you choose the second, I'll close this issue here.

**Comment by phax** [comment]
A separate folder called "Docker" with the respective files would be great - I'd like to keep it in this respository, for the sake of simplicity. And than we could even provide one for Peppol and one for other profiles if necessary. Thank you for your work!
