### ISSUE TITLE
Use server.jetty.address from test-phase4.properties in AS4ClientUserMessageTest

### ISSUE THREAD

**Issue by kukel** [phax/phase4#57]
A change in the `test-phase4.properties` of the `server.jetty.address` makes the tests in `AS4ClientUserMessageTest` fail

https://github.com/phax/phase4/blob/ab5305647f1f0d9a2424d2fe3d79622dc74c2a8e/phase4-test/src/test/java/com/helger/phase4/client/AS4ClientUserMessageTest.java#L65

Changing to
`
private static final String SERVER_URL = URLHelper.getAsURL (AS4Configuration.getConfig ().getAsString (MockJettySetup.SETTINGS_SERVER_ADDRESS)).toString();`

makes it work

(sorry, no pull request due to lack of access to my local tree)

**Comment by phax** [comment]
@kukel  Thanks for pointing that out. Fixed in master branch and will be part of the next 1.3.2 release

**Comment by kukel** [comment]
Found it out by accident due to some tomcat by accident running on port 8080
