### ISSUE TITLE
package com.helger.xservlet does not exist

### ISSUE THREAD

**Issue by reinhardt1053** [phax/phase4#70]
Hello, 

I compiled the source code from command line using: 
mvn clean install -U

I opened the project phase4-peppol-servlet in IntelliJ IDEA and the class AbstractXServlet is missing.  Searching over to your repositories I could find that class defined in the project ph-web. Should that be a dependency?

**Comment by phax** [comment]
The class is in project `ph-xservlet` which is transitively imported via `phase4-lib`:
```xml
    <dependency>
      <groupId>com.helger.web</groupId>
      <artifactId>ph-xservlet</artifactId>
    </dependency>
```

**Comment by phax** [comment]
@reinhardt1053 did you manage to resolve this issue?

**Comment by reinhardt1053** [comment]
Yes, thank you
