### ISSUE TITLE
Documentation Update - phase4.endpoint.address is actually required

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/phase4#74]
Hi,

So I ran into an issue sending messages to a phase4 server. I have the latest updates on both that server and the sender app. I got back an HTTP  400 with teh following message in the server logs:
[2021-12-21T20:10:35,111] [PEPPOL] [ERROR] [http-nio-18080-exec-3] HTTP 400: Bad Request: Error validating incoming AS4 message with the profile Peppol
 Following errors are present: [PMode.Leg[1].AddressProtocol 'http' is unsupported] -- com.helger.phase4.servlet.AS4UnifiedResponse.setResponseError(AS4UnifiedResponse.java:56)

After a lot of digging I found out that the property phase4.endpoint.address needs to be set to the server's https endpoint. After this change the message was successfully changed. 

I think you may need to update the documentation to highlight the importance of this field.

**Comment by phax** [comment]
@AlexandruCiobanu  thanks for pointing that out. I updated the documentation in the code as well as in the description of the configuration item
