### ISSUE TITLE
Is Phase4 integrated into enterprise applications, or is a single AP service available for multiple enterprises?  How does an independent AP service enterprise interact with this AP?

### ISSUE THREAD

**Issue by convicteva** [phax/phase4#75]

**Comment by phax** [comment]
The answer to your question is: Both is possible.
* In certain applications, phase4 is integrated as a library and serves as the AS4 endpoint to send and receive messages.
* In other setups, phase4 is running de-facto as a standalone-application and uses Database, file system or queuing systems to forward messages to other receivers. In this scenario, you as the implementer have the choice on how you want to offer senders the "sending" functionality. I personally prefer HTTP/REST interfaces to do so, but you are free to choose, whatever you like. There is no real "right" or "wrong" - it's up to your choice and and your infrastructure.

hth
