### ISSUE TITLE
Malformed XML document returned from SMP server

### ISSUE THREAD

**Issue by punithdj** [phax/phase4#76]
Hi Philip,
Above mentioned issue Is it because the receiver has not implemented yet the xrechnung_2.1 version and does, therefore, not recognize the new DocumentTypeID we are sending? Or something completely different?

**Comment by phax** [comment]
Hi @punithdj there is not general answer to your question.
Can you post the query URL here?

I expect this to be non-compliant response from the SMP but I can't tell without looking at it in detail

**Comment by phax** [comment]
This issue has been resolved, as it was an issue with the SMP of the other side.
