### ISSUE TITLE
When is the phase4 1.3.9 release scheduled?

### ISSUE THREAD

**Issue by tmhide** [phax/phase4#81]
I think phase4 1.3.9 will support Post-Award May 2022 Release in Peppol, because we are upgrading to phive-rules 2.1.13.
I would like to use this to support Post-Award May 2022 Release.
When is the phase4 1.3.9 release scheduled?

**Comment by phax** [comment]
You don't need to wait for phase4 to do this.
In your application, you simply need to update the `phive-rules` version in your build file to version `2.1.13` to use the updated rules.

E.g. in the Maven dependencies:
```xml
  <dependencyManagement>
    <dependencies>
...
      <dependency>
        <groupId>com.helger.phive.rules</groupId>
        <artifactId>phive-rules-parent-pom</artifactId>
        <version>2.1.13</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
...
    </dependencies>
  </dependencyManagement>
```

Please make sure, that the "phive-rules" are included BEFORE "phase4" to have precedence.
Then you can use the "3.14.0" validation rules
