### ISSUE TITLE
Embed country code in SBDH

### ISSUE THREAD

**Issue by sakasaka19** [phax/phase4#93]
Hello
Peppol's internal rules have changed and AccessPoint Providers are now obligated to submit a report on a monthly basis.
The report includes the country code of the sender and recipient.
With that, We need to embed those information into the SBDH at the time of transmission. 

Are you planning to support this in Phase4?
If so, in which version?
Specifically, I would like to know if there will be extensions to the PeppolSBDHDocument class and if there will be set functions like the setDocumentType function.

Best regards

**Comment by phax** [comment]
Hi @sakasaka19 
Please slow down :)
The Peppol rules **have not yet changed**

The new specification drafts were sent out for review, but the final specifications haven't yet been published.
So as long as no final specifications are out, no changes will be made to the software, to avoid unnecessary confusion.

As soon, as the new specifications are out, the necessary implementation changes will be done - most likely in the peppol-commons project as well as in phase4.

hth, Philip

**Comment by sakasaka19** [comment]
Oops, I'm getting ahead of myself.
Sorry.

Looking forward to upgrading Phase 4 after the new specs are released.

Thank you.
